---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest
    override_command: false
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
  enabled: false
